name: Run Unit Test via Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -U setuptools setuptools_scm wheel
          pip install flake8 pytest pytest-cov
          pip install -e .[all,testing]
      - name: unit test with pytest
        run: |
          pytest
    #     run: |
    #       coverage run -m pytest  -v -s
    #   - name: Generate Coverage Report
    #     run: |
    #       coverage report -m
